version: '3.8'

services:
  frontend:
    build:
      context: ./clays-fe
      dockerfile: Dockerfile
    container_name: react-frontend
    volumes:
      - ./frontend:/clays-fe
      - /clays-fe/node_modules
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0

  backend:
    build:
      context: ./clays-be
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
   
volumes:
  postgres_data:
